#!/usr/bin/env bash

SOLR_HOME=/home/mmoquillon/Applications/apache-solr-3.6.1/example
SOLR_PID=${SOLR_HOME}/solr.pid

case $1 in
  start)
    pushd ${SOLR_HOME}
    echo "Remove any previous data..."
    rm -rf solr/data 2>/dev/null
    echo "Start Apache Solr with clustering capabilities..."
    java -Dsolr.clustering.enabled=true -jar start.jar &
    echo $! > ${SOLR_PID}
    popd
    ;;
  stop)
    echo "Stop Apache Solr..."
    kill -15 `cat ${SOLR_PID}` &> /dev/null
    ;;
  status)
    pid=`cat ${SOLR_PID} 2> /dev/null`
    if [ $? -ne 0 ]; then
      echo "Apache Solr not running"
      exit 0
    fi
    ps $pid > /dev/null
    if [ $? -eq 0 ]; then
      echo "Apache Solr is running"
    else
      echo "Apache Solr not running"
    fi
    ;;
  *)
    echo "Usage: solr start|stop|status"
    ;;
esac

